#! /bin/sh

test -x /usr/bin/hhvm || exit 0

case "$1" in
  start)
    /usr/bin/hhvm --config /etc/hhvm/server.ini --user nginx --mode daemon -vServer.Type=fastcgi -vServer.Port=9000 -vLog.Level=Debug -vLog.File=/var/log/hhvm/hhvm.log
    ;;
  stop)
    start-stop-daemon --stop --quiet --oknodo --pidfile /var/run/hhvm/pid
    ;;

  reload|force-reload|restart|try-restart)
    $0 start
    $0 stop
    ;;

  status)
    echo "No status"
    ;;

  *)
    echo "Usage: /etc/init.d/hhvm-fastcgi {start|stop|restart|status}"
    exit 1
esac

exit 0
